Trigger redeploy

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -50,6 +50,13 @@ jobs:
           echo "Waiting 5 seconds for namespace to be registered..."
           sleep 5
 
+      - name: Verify Namespace Creation
+        run: |
+          kubectl get namespace airflow || {
+            echo "Namespace 'airflow' is missing. Applying namespace manifest.";
+            kubectl apply -f k8s/airflow-namespace.yaml;
+          }
+
       - name: Apply rest of manifests
         run: |
           kubectl apply -f k8s/
@@ -72,7 +79,7 @@ jobs:
           kubectl wait pod -n airflow \
             --for=condition=Ready \
             -l app=airflow-webserver \
-            --timeout=2000s || {
+            --timeout=3000s || {
               echo "Webserver pod didn't become ready immediately. Waiting 10 seconds before checking again..."
               sleep 10
               
@@ -89,6 +96,12 @@ jobs:
                 }
             }
           echo "Webserver pod is ready!"
+
+      - name: Debug Airflow Deployment
+        run: |
+          kubectl get all -n airflow;
+          kubectl describe pods -n airflow;
+          kubectl logs -n airflow -l app=airflow-webserver --all-containers=true;
 
       - name: Get Webserver Pod Name
         id: get-pod
